version: '3.1'

services:

  db-api-solid-pg:
    image: bitnami/postgresql
    container_name: db-api-solid-pg
    restart: always
    environment:
      POSTGRESQL_USERNAME: docker
      POSTGRESQL_PASSWORD: docker
      POSTGRESQL_DATABASE: dbsolid
    ports:
      - 5432:5432
    volumes:
      - db_pg:/bitnami/postgresql

volumes:
  db_pg:

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
